import assert from 'node:assert/strict';
import {watchNavigation,followNavigation,newDestination} from '../chrome_navigation.mjs';
const source='https://example.org/',destination='https://search.example.org/?q=cats';
const contract={observation_policy:'public_ui',scope:{origins:['https://example.org','https://search.example.org']},inputs:{query:{value:'cats'}},success:[{kind:'url_query',parameter:'q',input_ref:'query'}]};
const before=new Set(['1','2']);
assert.equal(newDestination({id:'2',url:destination},before,contract,null),false);
assert.equal(newDestination({id:'3',url:'https://unrelated.invalid/?q=cats'},before,contract,null),false);
assert.equal(newDestination({id:'3',url:'https://search.example.org/?q=dogs'},before,contract,null),false);
assert.equal(newDestination({id:'3',url:destination},before,contract,null),true);
assert.equal(newDestination({id:'3',url:'https://example.org/watch?id=2'},before,{...contract,success:[]},'https://example.org/watch?id=1'),false);
const detailGoal={...contract,success:[{kind:'exists',target:{role:'button',name:'Details'}}]};
assert.equal(newDestination({id:'3',url:destination},before,detailGoal,null,'cats'),true);
assert.equal(newDestination({id:'3',url:'https://search.example.org/?q=cats&q=dogs'},before,detailGoal,null,'cats'),false);
assert.equal(newDestination({id:'3',url:destination},before,detailGoal,null,'dogs'),false);
const pathGoal={...contract,success:[{kind:'url_path_prefix',equals:'/items/'}]};
assert.equal(newDestination({id:'3',url:'https://example.org/items/123?tracking=changed'},before,pathGoal,null),true);
assert.equal(newDestination({id:'3',url:'https://example.org/items/'},before,pathGoal,null),false);
assert.equal(newDestination({id:'3',url:'https://example.org/items-old/123'},before,pathGoal,null),false);
const initial={async url(){return source;},id:'1'};const child={async url(){return destination;},id:'3'};
let meta=[{id:'1',url:source},{id:'2',url:destination}],claimed=0,tracked=[];
const driver={contract,tab:initial,tabs:new Map([['1',{tab:initial,owned:true}]]),lifecycle:{track(...args){tracked.push(args);}},browser:{user:{async openTabs(){return meta;},async claimTab(value){assert.equal(value.id,'3');claimed++;return child;}}}};
const box={role:'searchbox',attributes:{public_search:'true'}};
const watch=await watchNavigation(driver,box,'key','Enter');
meta.push({id:'3',url:destination});assert.equal(await followNavigation(driver,watch),true);
assert.equal(driver.tab,child);assert.equal(claimed,1);assert.equal(driver.tabs.get('3').owned,false);assert.equal(tracked[0][2],false);
driver.tab=initial;meta.push({id:'4',url:destination});
await assert.rejects(followNavigation(driver,watch),/CHROME_TAB_NOT_UNIQUE/);assert.equal(claimed,1);
meta=[{id:'1',url:source},{id:'2',url:destination}];driver.tab={async url(){return destination;}};
assert.equal(await followNavigation(driver,watch),false);assert.equal(claimed,1);
driver.tab={async url(){return source+'?tracking=changed';}};meta.push({id:'3',url:destination});
assert.equal(await followNavigation(driver,watch),true);assert.equal(claimed,2);
assert.equal(await watchNavigation({...driver,contract:{...contract,observation_policy:'allowlist'}},box,'key','Enter'),null);
console.log(JSON.stringify({status:'PASS',checks:19,mode:'new-page regression: intermediate search, detail path prefixes, existing-tab exclusion, origins, input identity, ambiguity and ownership'}));
